# Generated by Django 3.2.4 on 2021-07-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_profile_nav',
            name='my_kaggle_link',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='my_kaggle_link'),
        ),
    ]
