# Generated by Django 3.2.4 on 2021-07-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_my_profile_nav_my_kaggle_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_profile_home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('my_job_status', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_intro', models.TextField(blank=True, max_length=600, null=True)),
                ('side_profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('what_i_do', models.TextField(blank=True, max_length=600, null=True)),
            ],
        ),
    ]
