# Generated by Django 3.2.4 on 2021-07-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_my_profile_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='testiomonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_details', models.TextField(blank=True, max_length=800, null=True)),
                ('test_name', models.CharField(blank=True, max_length=100, null=True)),
                ('test_job_status', models.CharField(blank=True, max_length=200, null=True)),
                ('test_profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
