# Generated by Django 3.2.4 on 2021-07-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_my_blog_my_portfolio_my_research'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_research',
            name='research_readtime',
        ),
        migrations.AddField(
            model_name='my_research',
            name='research_publication_link',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='my_kaggle_link'),
        ),
    ]
