# Generated by Django 3.2.4 on 2021-07-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0006_auto_20210712_1825'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='My_research',
            new_name='My_researche',
        ),
    ]
