# Generated by Django 3.2.4 on 2021-07-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0008_auto_20210712_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_researche',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
