# Generated by Django 3.2.4 on 2021-07-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0009_my_researche_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_researche',
            name='status',
        ),
        migrations.AddField(
            model_name='my_researche',
            name='Featured',
            field=models.IntegerField(choices=[(0, 'not_featured'), (1, 'Featured')], default=0),
        ),
    ]
