# Generated by Django 3.2.4 on 2021-07-12 20:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0010_auto_20210712_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_blog',
            name='Featured',
            field=models.IntegerField(choices=[(0, 'not_featured'), (1, 'Featured')], default=0),
        ),
        migrations.AddField(
            model_name='my_blog',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 7, 12, 20, 44, 0, 349940, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='my_portfolio',
            name='Featured',
            field=models.IntegerField(choices=[(0, 'not_featured'), (1, 'Featured')], default=0),
        ),
        migrations.AddField(
            model_name='my_portfolio',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 7, 12, 20, 44, 7, 70330, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='my_researche',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 7, 12, 20, 44, 14, 662393, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
