# Generated by Django 3.2.4 on 2021-07-12 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0011_auto_20210712_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_blog',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='my_portfolio',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='my_researche',
            name='created_on',
        ),
    ]
