# Generated by Django 3.2.4 on 2021-07-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0013_auto_20210712_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_profile_nav',
            name='my_email',
            field=models.URLField(blank=True, db_index=True, max_length=128, verbose_name='my_email'),
        ),
        migrations.AddField(
            model_name='my_profile_nav',
            name='my_ig',
            field=models.URLField(blank=True, db_index=True, max_length=128, verbose_name='my_ig_link'),
        ),
        migrations.AddField(
            model_name='my_profile_nav',
            name='my_medium_link',
            field=models.URLField(blank=True, db_index=True, max_length=128, verbose_name='my_medium_link'),
        ),
        migrations.AddField(
            model_name='my_profile_nav',
            name='my_stack_overflow',
            field=models.URLField(blank=True, db_index=True, max_length=128, verbose_name='my_stack_overflow'),
        ),
        migrations.AddField(
            model_name='my_profile_nav',
            name='my_twitter',
            field=models.URLField(blank=True, db_index=True, max_length=128, verbose_name='my_twitter_link'),
        ),
        migrations.AlterField(
            model_name='my_profile_nav',
            name='facebook_link',
            field=models.URLField(blank=True, db_index=True, max_length=128, verbose_name='facebook_link'),
        ),
        migrations.AlterField(
            model_name='my_profile_nav',
            name='github_link',
            field=models.URLField(blank=True, db_index=True, max_length=128, verbose_name='github_link'),
        ),
        migrations.AlterField(
            model_name='my_profile_nav',
            name='google_sch_link',
            field=models.URLField(blank=True, db_index=True, max_length=128, verbose_name='google_sch_link'),
        ),
        migrations.AlterField(
            model_name='my_profile_nav',
            name='linkedin_link',
            field=models.URLField(blank=True, db_index=True, max_length=128, verbose_name='linkedin_link'),
        ),
        migrations.AlterField(
            model_name='my_profile_nav',
            name='my_kaggle_link',
            field=models.URLField(blank=True, db_index=True, max_length=128, verbose_name='my_kaggle_link'),
        ),
        migrations.AlterField(
            model_name='my_profile_nav',
            name='my_website_link',
            field=models.URLField(blank=True, db_index=True, max_length=128, verbose_name='my_website_link'),
        ),
        migrations.AlterField(
            model_name='my_profile_nav',
            name='researchgate_link',
            field=models.URLField(blank=True, db_index=True, max_length=128, verbose_name='researchgate_link'),
        ),
    ]
