# Generated by Django 3.2.4 on 2021-07-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0015_my_profile_nav_my_facebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_profile_nav',
            name='my_email',
            field=models.EmailField(blank=True, db_index=True, max_length=128, verbose_name='my_email'),
        ),
    ]
