# Generated by Django 3.2.4 on 2021-07-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0016_alter_my_profile_nav_my_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_name', models.CharField(blank=True, max_length=100, null=True)),
                ('con_email', models.EmailField(blank=True, db_index=True, max_length=128, verbose_name='my_email')),
                ('message', models.TextField(blank=True, max_length=600, null=True)),
            ],
        ),
    ]
