# Generated by Django 3.2.4 on 2021-07-13 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0017_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='con_message',
        ),
    ]
