# Generated by Django 3.2.4 on 2021-08-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0018_rename_message_contact_con_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_portfolio',
            name='portfolio_live_link',
            field=models.URLField(blank=True, db_index=True, max_length=128, verbose_name='portfolio_live_link'),
        ),
    ]
